#3_1_2_4
for i in range(10):
    print("The value of i is currently", i)

for i in range(2, 8):
    print("The value of i is currently", i)

for i in range (2, 8, 3):  #3rd argument = increment/toename, added to control the variable at every loop turn.
    print("The value of i is currently", i)
#1st argument passed to the range() function indicates the starting number of the sequence
#2nd argument tells the function where to stop the sequence
#3rd argument indicates the step: difference between each number in the sequence
#of numbers generated by the function.
#vb: 2 (starting nr) -> 5 (2 neemt toe met 3 = 5/ligt binnen de range 2-8)
#-> 8 (5 neemt toe met 3 = 8 ligt buiten de range want the stop parameter
# wordt niet meegenomen in de sequence)

pow = 1
for exp in tange(16):
    print("2 to the poewer of", exp, "is", pow)
    pow *= 2
#The exp variable is used as a control variable for the loop, and indicates the 
# current value of the exponent. The exponentiation itself is replaced by multiplying 
# by two. Since 20 is equal to 1, then 2 × 1 is equal to 21, 2 × 21 is equal to 22, and so on. 
# What is the greatest exponent for which our program still prints the result?
#15 want 16 wordt niet meegenomen....